# Generated by Django 5.2.9 on 2025-12-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
