# Generated by Django 5.2.9 on 2025-12-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
